import{a as m,S as w,i}from"./assets/vendor-Z6SuAarM.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();m.defaults.baseURL="https://pixabay.com/api";async function h(n,r=1){return(await m.get("/",{params:{key:"54497061-8a3f1039e79f08659d000d130",image_type:"photo",lang:"en",orientation:"horizontal",safesearch:!0,per_page:15,page:r,q:n}})).data}const f=document.querySelector(".loader"),p=document.querySelector(".load-btn");var S=new w(".gallery a",{});function y(n){const r=n.map(e=>`
	<li class="imageCard" >
		<a href="${e.largeImageURL}">
			<img  src="${e.webformatURL}" alt="${e.tags}">
		</a>
		<div class="captions">
			<p><strong>Likes:</strong> ${e.likes}</p>
			<p><strong>views:</strong> ${e.views}</p>
			<p><strong>Comments:</strong> ${e.comments}</p>
			<p><strong>Downloads:</strong> ${e.downloads}</p>
		</div>
	</li>`).join("");return document.querySelector(".gallery").insertAdjacentHTML("beforeend",r),S.refresh(),0}function b(){document.querySelector(".gallery").innerHTML=""}function L(){f.classList.remove("hidden")}function u(){f.classList.add("hidden")}function v(){p.classList.remove("hidden")}function g(){p.classList.add("hidden")}let s=1,c=1;const q=15;let l;const R=document.querySelector(".form");R.addEventListener("submit",C);const B=document.querySelector(".load-btn");B.addEventListener("click",M);async function C(n){if(n.preventDefault(),l=n.target.elements["search-text"].value,l.trim()!==""){b(),s=1,L();try{const e=await h(l,s);e.hits.length===0?i.error({title:"",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}):(y(e.hits),v(),u()),c=Math.round(e.totalHits/q),(c==s||c==0)&&(g(),i.info({title:"",position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({title:"Error",message:"Something went wrong.",position:"topRight"})}}}async function M(n){s+=1,g(),L();try{const r=await h(l,s);y(r.hits),P(),c==s?(g(),u(),i.info({title:"",position:"topRight",message:"We're sorry, but you've reached the end of search results."})):(v(),u())}catch{i.error({title:"Error",message:"Something went wrong.",position:"topRight"})}}function P(){const a={top:document.querySelector(".imageCard").getBoundingClientRect().height*2,behavior:"smooth"};scrollBy(a)}
//# sourceMappingURL=index.js.map
