import{a as m,S as w,i}from"./assets/vendor-Z6SuAarM.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&c(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();m.defaults.baseURL="https://pixabay.com/api";async function h(s,r=1){return(await m.get("/",{params:{key:"54497061-8a3f1039e79f08659d000d130",image_type:"photo",lang:"en",orientation:"horizontal",safesearch:!0,per_page:15,page:r,q:s}})).data}const f=document.querySelector(".loader"),p=document.querySelector(".load-btn");var S=new w(".gallery a",{});function y(s){const r=s.map(e=>`
	<li class="imageCard" >
		<a href="${e.largeImageURL}">
			<img  src="${e.webformatURL}" alt="${e.tags}">
		</a>
		<div class="captions">
			<p><strong>Likes:</strong> ${e.likes}</p>
			<p><strong>views:</strong> ${e.views}</p>
			<p><strong>Comments:</strong> ${e.comments}</p>
			<p><strong>Downloads:</strong> ${e.downloads}</p>
		</div>
	</li>`).join("");return document.querySelector(".gallery").insertAdjacentHTML("beforeend",r),S.refresh(),0}function b(){document.querySelector(".gallery").innerHTML=""}function L(){f.classList.remove("hidden")}function d(){f.classList.add("hidden")}function v(){p.classList.remove("hidden")}function a(){p.classList.add("hidden")}let n=1,g=1;const q=15;let l;const R=document.querySelector(".form");R.addEventListener("submit",C);const B=document.querySelector(".load-btn");B.addEventListener("click",M);async function C(s){if(s.preventDefault(),l=s.target.elements["search-text"].value,l.trim()!==""){a(),L(),b(),n=1;try{const e=await h(l,n);e.hits.length===0?(i.error({title:"",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),d()):(y(e.hits),v(),d()),g=Math.ceil(e.totalHits/q),g==n&&(i.info({title:"",position:"topRight",message:"We're sorry, but you've reached the end of search results."}),a())}catch{hideLoad(),a(),i.error({title:"Error",message:"Something went wrong.",position:"topRight"})}}}async function M(s){n+=1,a(),L();try{const r=await h(l,n);y(r.hits),P(),g==n?(a(),d(),i.info({title:"",position:"topRight",message:"We're sorry, but you've reached the end of search results."})):(v(),d())}catch{hideLoad(),i.error({title:"Error",message:"Something went wrong.",position:"topRight"})}}function P(){const c={top:document.querySelector(".imageCard").getBoundingClientRect().height*2,behavior:"smooth"};scrollBy(c)}
//# sourceMappingURL=index.js.map
