import{a as m,S as w,i as a}from"./assets/vendor-Z6SuAarM.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&l(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();m.defaults.baseURL="https://pixabay.com/api";async function h(s,r=1){return(await m.get("/",{params:{key:"54497061-8a3f1039e79f08659d000d130",image_type:"photo",lang:"en",orientation:"horizontal",safesearch:!0,per_page:15,page:r,q:s}})).data}const f=document.querySelector(".loader"),p=document.querySelector(".load-btn");var S=new w(".gallery a",{});function y(s){const r=s.map(e=>`
	<li class="imageCard" >
		<a href="${e.largeImageURL}">
			<img  src="${e.webformatURL}" alt="${e.tags}">
		</a>
		<div class="captions">
			<p><strong>Likes:</strong> ${e.likes}</p>
			<p><strong>views:</strong> ${e.views}</p>
			<p><strong>Comments:</strong> ${e.comments}</p>
			<p><strong>Downloads:</strong> ${e.downloads}</p>
		</div>
	</li>`).join("");return document.querySelector(".gallery").insertAdjacentHTML("beforeend",r),S.refresh(),0}function b(){document.querySelector(".gallery").innerHTML=""}function L(){f.classList.remove("hidden")}function n(){f.classList.add("hidden")}function v(){p.classList.remove("hidden")}function c(){p.classList.add("hidden")}let i=1,g=1;const q=15;let d;const R=document.querySelector(".form");R.addEventListener("submit",C);const B=document.querySelector(".load-btn");B.addEventListener("click",M);async function C(s){if(s.preventDefault(),d=s.target.elements["search-text"].value,d.trim()!==""){c(),L(),b(),i=1;try{const e=await h(d,i);e.hits.length===0?(a.error({title:"",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),n()):(y(e.hits),v(),n()),g=Math.ceil(e.totalHits/q),g==i&&(a.info({title:"",position:"topRight",message:"We're sorry, but you've reached the end of search results."}),c())}catch{n(),c(),a.error({title:"Error",message:"Something went wrong.",position:"topRight"})}}}async function M(s){i+=1,c(),L();try{const r=await h(d,i);y(r.hits),P(),g==i?(c(),n(),a.info({title:"",position:"topRight",message:"We're sorry, but you've reached the end of search results."})):(v(),n())}catch{n(),a.error({title:"Error",message:"Something went wrong.",position:"topRight"})}}function P(){const l={top:document.querySelector(".imageCard").getBoundingClientRect().height*2,behavior:"smooth"};scrollBy(l)}
//# sourceMappingURL=index.js.map
